// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acgqsmgcajfsevxkcrfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjZ3FzbWdjYWpmc2V2eGtjcmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjYyNjMsImV4cCI6MjA2ODU0MjI2M30.rYEzIFaxJUPz0UkowJ8Rpu7sLDUG6IwhK2I2ev9tXZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});